Network Review CI Improvements

diff --git a/.github/workflows/review.yml b/.github/workflows/review.yml
--- a/.github/workflows/review.yml
+++ b/.github/workflows/review.yml
@@ -16,15 +16,19 @@ jobs:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
-        node-version: 20
+        node-version: 22
+    - name: Verify Review Script
+      run: |
+        git fetch https://github.com/safe-global/safe-deployments.git main:safe-global-main
+        if ! git diff --exit-code safe-global-main -- . ':!src/assets'; then
+          echo "ERROR: GitHub review script may not be up-to-date" 1>&2
+          exit 1
+        fi
+    - name: Install Dependencies
+      run: |
+        npm ci
     - name: Review PR
       env:
         GH_TOKEN: ${{ github.token }}
       run: |
-        git fetch https://github.com/safe-global/safe-deployments.git main:safe-global-main
-        if ! git diff --exit-code safe-global-main -- bin/github-review.sh; then
-          echo "ERROR: GitHub review script is not up-to-date" 1>&2
-          exit 1
-        fi
-        npm ci
         bash bin/github-review.sh ${{ github.event.number }}
