Run on PR Branch
This PR changes the review script to run on the PR branch in CI instead
of trying to apply changes to the branch. This is done to avoid issues
where merges to `main` cause PRs to no longer review properly.

In the past, we made these changes in order to ensure that the script
gets run as-expected from `main` to make sure that PRs couldn't change
the scripts and cause them to pass, but this is now ensured by the
GitHub action itself.

diff --git a/.github/workflows/review.yml b/.github/workflows/review.yml
--- a/.github/workflows/review.yml
+++ b/.github/workflows/review.yml
@@ -14,8 +14,6 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
-      with:
-        ref: main
     - uses: actions/setup-node@v4
       with:
         node-version: 20
@@ -23,5 +21,10 @@ jobs:
       env:
         GH_TOKEN: ${{ github.token }}
       run: |
+        git fetch origin main
+        if ! git diff --exit-code main -- bin/github-review.sh; then
+          echo "ERROR: GitHub review script is not up-to-date" 1>&2
+          exit 1
+        fi
         npm ci
         bash bin/github-review.sh ${{ github.event.number }}
